services:
  chatbot2k:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./static:/app/static
      - ./storage:/app/storage
      - ./data:/app/data
    env_file:
      - .env
